### PR TITLE
Translated 4 articles to proper Polish

### PR DESCRIPTION
**Pull request by asdfMaciej**
Hey, I noticed that the repo is autotranslated. I helped with starting a proper translation - I have changed 4 articles.

### CODE REVIEW

**Comment by gosali** [comment]
Hello, @asdfMaciej , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
Hello, @asdfMaciej 

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The suggestion will be merged to this repository.  We will release this article on the next localization release round. 
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request merged**
